name: "Setup For GNU Test"
description: "Setup For GNU Test"
inputs:
  path:
    description: "default to ./target/${BUILD_PROFILE}/"
    required: false
    default: ""
  artifacts:
    description: "Artifacts to download, only works with s3/gcs"
    required: false
    default: "meta,query"
runs:
  using: "composite"
  steps:
    - id: target
      shell: bash
      run: |
        arch=$(uname -m)
        target="${arch}-unknown-linux-gnu"
        echo "target=${target}" >> $GITHUB_OUTPUT

    - uses: ./.github/actions/setup_bendsql

    - uses: ./.github/actions/artifact_download
      with:
        sha: ${{ github.sha }}
        target: ${{ steps.target.outputs.target }}
        category: full
        artifacts: ${{ inputs.artifacts }}
        path: ${{ inputs.path }}

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Configure pip to use alternative mirror
      shell: bash
      run: |
        # Create pip config directory
        mkdir -p ~/.config/pip
        # Configure pip to use Google's PyPI mirror exclusively
        echo "[global]
        index-url = https://us-python.pkg.dev/pypi/pypi/simple/
        trusted-host = us-python.pkg.dev" > ~/.config/pip/pip.conf
        # Apply the configuration immediately for the setup-python action
        export PIP_INDEX_URL=https://us-python.pkg.dev/pypi/pypi/simple/
        export PIP_TRUSTED_HOST=us-python.pkg.dev
        
        # Upgrade pip using the configured mirror
        python -m pip install --upgrade pip --no-cache-dir

    - name: Install Python packages
      shell: bash
      run: |
        pip install rich
        pip install databend_driver
        pip install duckdb

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "11"

    - name: setup java env
      shell: bash
      run: |
        echo "LD_LIBRARY_PATH=${{ env.JAVA_HOME }}/lib/server:${{ env.LD_LIBRARY_PATH }}" >> $GITHUB_ENV
