[package]
name = "common-arrow"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies] # In alphabetical order
# Workspace dependencies

# Github dependencies
arrow = { version = "4.0" }
arrow-flight = { version = "4.0" }
parquet = { version = "4.0", features = ["arrow"] }

# Crates.io dependencies

[dev-dependencies]
