[package]
name = "common-storages-stage"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-compress = { path = "../../../common/compress" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-formats = { path = "../../formats" }
common-meta-app = { path = "../../../meta/app" }
common-pipeline-core = { path = "../../pipeline/core" }
common-pipeline-sources = { path = "../../pipeline/sources" }
common-pipeline-transforms = { path = "../../pipeline/transforms" }
common-storage = { path = "../../../common/storage" }

async-backtrace = { workspace = true }
async-trait = { workspace = true }
dashmap = "5.4.0"
log = { workspace = true }
opendal = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }

typetag = "0.2.6"
uuid = { version = "1.1.2", features = ["serde", "v4"] }

[build-dependencies]
common-building = { path = "../../../common/building" }
