[package]
name = "common-raft-store"
version = "0.1.0"
description = "distributed meta data service"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
common-exception = {path = "../exception"}
common-metatypes = {path = "../metatypes"}
common-planners = {path = "../planners"}
common-base = {path = "../base" }
common-sled-store = {path = "../sled-store"}
common-tracing = {path = "../tracing"}

anyhow = "1.0.44"
async-raft = { git = "https://github.com/datafuse-extras/async-raft", tag = "v0.6.2-alpha.16" }
async-trait = "0.1"
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
structopt-toml = "0.5.0"
maplit = "1.0.2"


[dev-dependencies]
pretty_assertions = "1.0"
tempfile = "3.2.0"
