[package]
name = "common-metatypes"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
common-sled-store = {path = "../sled-store"}

serde = { version = "1.0", features = ["derive"] }
async-raft = { git = "https://github.com/datafuse-extras/async-raft", tag = "v0.6.2-alpha.16" }

[dev-dependencies]
pretty_assertions = "1.0"
