name: Performance(Standalone)
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Tests"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Rust setup
        run: |
          bash ./scripts/setup/dev_setup.sh

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Run Performance Tests with Standalone mode
        run: |
          bash ./scripts/ci/ci-performance-tests-standalone.sh
