name: Performance(Standalone)
on:
  issue_comment:
    types: [created, edited, deleted]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Tests"
    if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: self-hosted
    steps:
      - name: dependency hack on self hosted machine
        if: contains(github.event.comment.body, '/runperf')
        run: |
          sudo wget http://archive.ubuntu.com/ubuntu/pool/main/p/psmisc/psmisc_23.3-1_amd64.deb
          sudo dpkg -i ./psmisc_23.3-1_amd64.deb
          sudo apt-get update
          sudo apt-get install mysql-client -y
          sudo apt-get install -y --no-install-recommends ca-certificates
          sudo apt-get install -y --no-install-recommends build-essential
          sudo apt-get install -y --no-install-recommends cmake
          sudo apt-get install -y --no-install-recommends clang
          sudo apt-get install -y --no-install-recommends llvm
          sudo apt-get install -y --no-install-recommends pkg-config
          sudo apt-get install -y --no-install-recommends lcov
          sudo apt-get install -y --no-install-recommends python3
          sudo apt-get install -y --no-install-recommends coreutils
          sudo apt-get install -y --no-install-recommends python3-all-dev
          sudo apt-get install -y --no-install-recommends python3-setuptools
          sudo apt-get install -y --no-install-recommends python3-pip
          sudo apt-get install -y --no-install-recommends git


      - name: Install latest nightly
        if: contains(github.event.comment.body, '/runperf')
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory
      - name: Run cargo check
        if: steps.check.outputs.triggered == 'true'
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Build native release
        if: contains(github.event.comment.body, '/runperf')
        run: |
          bash ./scripts/ci/ci-native-release-build.sh

      - name: Run Performance Tests with Standalone mode
        if: contains(github.event.comment.body, '/runperf')
        run: |
          bash ./scripts/ci/ci-performance-tests-standalone.sh
          
